export interface PlumbingArea {
    name: string;
    /**น้้าประปานครหลวง = MWA*/
    MWA: boolean;
    /**น้้าประปาส่วนภูมิภาค = PWA */
    PWA: boolean;
    Other: boolean;
}

export const provinceData: PlumbingArea[] = [
    { MWA: true, PWA: false, Other: true, name: 'กรุงเทพมหานคร' },
    { MWA: true, PWA: false, Other: true, name: 'นนทบุรี' },
    { MWA: true, PWA: false, Other: true, name: 'สมุทรปราการ' },
    { MWA: true, PWA: true, Other: true, name: 'นครปฐม' },
    { MWA: true, PWA: true, Other: true, name: 'สมุทรสาคร' },
    { MWA: true, PWA: true, Other: true, name: 'ปทุมธานี' },
    { MWA: false, PWA: true, Other: true, name: 'พระนครศรีอยุธยา' },
    { MWA: false, PWA: true, Other: true, name: 'อ่างทอง' },
    { MWA: false, PWA: true, Other: true, name: 'ลพบุรี' },
    { MWA: false, PWA: true, Other: true, name: 'สิงห์บุรี' },
    { MWA: false, PWA: true, Other: true, name: 'ชัยนาท' },
    { MWA: false, PWA: true, Other: true, name: 'สระบุรี' },
    { MWA: false, PWA: true, Other: true, name: 'ชลบุรี' },
    { MWA: false, PWA: true, Other: true, name: 'ระยอง' },
    { MWA: false, PWA: true, Other: true, name: 'จันทบุรี' },
    { MWA: false, PWA: true, Other: true, name: 'ตราด' },
    { MWA: false, PWA: true, Other: true, name: 'ฉะเชิงเทรา' },
    { MWA: false, PWA: true, Other: true, name: 'ปราจีนบุรี' },
    { MWA: false, PWA: true, Other: true, name: 'นครนายก' },
    { MWA: false, PWA: true, Other: true, name: 'สระแก้ว' },
    { MWA: false, PWA: true, Other: true, name: 'นครราชสีมา' },
    { MWA: false, PWA: true, Other: true, name: 'บุรีรัมย์' },
    { MWA: false, PWA: true, Other: true, name: 'สุรินทร์' },
    { MWA: false, PWA: true, Other: true, name: 'ศรีสะเกษ' },
    { MWA: false, PWA: true, Other: true, name: 'อุบลราชธานี' },
    { MWA: false, PWA: true, Other: true, name: 'ยโสธร' },
    { MWA: false, PWA: true, Other: true, name: 'ชัยภูมิ' },
    { MWA: false, PWA: true, Other: true, name: 'อำนาจเจริญ' },
    { MWA: false, PWA: true, Other: true, name: 'บึงกาฬ' },
    { MWA: false, PWA: true, Other: true, name: 'หนองบัวลำภู' },
    { MWA: false, PWA: true, Other: true, name: 'ขอนแก่น' },
    { MWA: false, PWA: true, Other: true, name: 'อุดรธานี' },
    { MWA: false, PWA: true, Other: true, name: 'เลย' },
    { MWA: false, PWA: true, Other: true, name: 'หนองคาย' },
    { MWA: false, PWA: true, Other: true, name: 'มหาสารคาม' },
    { MWA: false, PWA: true, Other: true, name: 'ร้อยเอ็ด' },
    { MWA: false, PWA: true, Other: true, name: 'กาฬสินธุ์' },
    { MWA: false, PWA: true, Other: true, name: 'สกลนคร' },
    { MWA: false, PWA: true, Other: true, name: 'นครพนม' },
    { MWA: false, PWA: true, Other: true, name: 'มุกดาหาร' },
    { MWA: false, PWA: true, Other: true, name: 'เชียงใหม่' },
    { MWA: false, PWA: true, Other: true, name: 'ลำพูน' },
    { MWA: false, PWA: true, Other: true, name: 'ลำปาง' },
    { MWA: false, PWA: true, Other: true, name: 'อุตรดิตถ์' },
    { MWA: false, PWA: true, Other: true, name: 'แพร่' },
    { MWA: false, PWA: true, Other: true, name: 'น่าน' },
    { MWA: false, PWA: true, Other: true, name: 'พะเยา' },
    { MWA: false, PWA: true, Other: true, name: 'เชียงราย' },
    { MWA: false, PWA: true, Other: true, name: 'แม่ฮ่องสอน' },
    { MWA: false, PWA: true, Other: true, name: 'นครสวรรค์' },
    { MWA: false, PWA: true, Other: true, name: 'อุทัยธานี' },
    { MWA: false, PWA: true, Other: true, name: 'กำแพงเพชร' },
    { MWA: false, PWA: true, Other: true, name: 'ตาก' },
    { MWA: false, PWA: true, Other: true, name: 'สุโขทัย' },
    { MWA: false, PWA: true, Other: true, name: 'พิษณุโลก' },
    { MWA: false, PWA: true, Other: true, name: 'พิจิตร' },
    { MWA: false, PWA: true, Other: true, name: 'เพชรบูรณ์' },
    { MWA: false, PWA: true, Other: true, name: 'ราชบุรี' },
    { MWA: false, PWA: true, Other: true, name: 'กาญจนบุรี' },
    { MWA: false, PWA: true, Other: true, name: 'สุพรรณบุรี' },
    { MWA: false, PWA: true, Other: true, name: 'สมุทรสงคราม' },
    { MWA: false, PWA: true, Other: true, name: 'เพชรบุรี' },
    { MWA: false, PWA: true, Other: true, name: 'ประจวบคีรีขันธ์' },
    { MWA: false, PWA: true, Other: true, name: 'นครศรีธรรมราช' },
    { MWA: false, PWA: true, Other: true, name: 'กระบี่' },
    { MWA: false, PWA: true, Other: true, name: 'พังงา' },
    { MWA: false, PWA: true, Other: true, name: 'ภูเก็ต' },
    { MWA: false, PWA: true, Other: true, name: 'สุราษฎร์ธานี' },
    { MWA: false, PWA: true, Other: true, name: 'ระนอง' },
    { MWA: false, PWA: true, Other: true, name: 'ชุมพร' },
    { MWA: false, PWA: true, Other: true, name: 'สงขลา' },
    { MWA: false, PWA: true, Other: true, name: 'สตูล' },
    { MWA: false, PWA: true, Other: true, name: 'ตรัง' },
    { MWA: false, PWA: true, Other: true, name: 'พัทลุง' },
    { MWA: false, PWA: true, Other: true, name: 'ปัตตานี' },
    { MWA: false, PWA: true, Other: true, name: 'ยะลา' },
    { MWA: false, PWA: true, Other: true, name: 'นราธิวาส' },
]


