export interface Item {
    code: string;
    name: string;
}

export const provinceData: Item[] = [
    { code: '10', name: 'กรุงเทพมหานคร' },
    { code: '11', name: 'สมุทรปราการ' },
    { code: '12', name: 'นนทบุรี' },
    { code: '13', name: 'ปทุมธานี' },
    { code: '14', name: 'พระนครศรีอยุธยา' },
    { code: '15', name: 'อ่างทอง' },
    { code: '16', name: 'ลพบุรี' },
    { code: '17', name: 'สิงห์บุรี' },
    { code: '18', name: 'ชัยนาท' },
    { code: '19', name: 'สระบุรี' },
    { code: '20', name: 'ชลบุรี' },
    { code: '21', name: 'ระยอง' },
    { code: '22', name: 'จันทบุรี' },
    { code: '23', name: 'ตราด' },
    { code: '24', name: 'ฉะเชิงเทรา' },
    { code: '25', name: 'ปราจีนบุรี' },
    { code: '26', name: 'นครนายก' },
    { code: '27', name: 'สระแก้ว' },
    { code: '30', name: 'นครราชสีมา' },
    { code: '31', name: 'บุรีรัมย์' },
    { code: '32', name: 'สุรินทร์' },
    { code: '33', name: 'ศรีสะเกษ' },
    { code: '34', name: 'อุบลราชธานี' },
    { code: '35', name: 'ยโสธร' },
    { code: '36', name: 'ชัยภูมิ' },
    { code: '37', name: 'อำนาจเจริญ' },
    { code: '38', name: 'บึงกาฬ' },
    { code: '39', name: 'หนองบัวลำภู' },
    { code: '40', name: 'ขอนแก่น' },
    { code: '41', name: 'อุดรธานี' },
    { code: '42', name: 'เลย' },
    { code: '43', name: 'หนองคาย' },
    { code: '44', name: 'มหาสารคาม' },
    { code: '45', name: 'ร้อยเอ็ด' },
    { code: '46', name: 'กาฬสินธุ์' },
    { code: '47', name: 'สกลนคร' },
    { code: '48', name: 'นครพนม' },
    { code: '49', name: 'มุกดาหาร' },
    { code: '50', name: 'เชียงใหม่' },
    { code: '51', name: 'ลำพูน' },
    { code: '52', name: 'ลำปาง' },
    { code: '53', name: 'อุตรดิตถ์' },
    { code: '54', name: 'แพร่' },
    { code: '55', name: 'น่าน' },
    { code: '56', name: 'พะเยา' },
    { code: '57', name: 'เชียงราย' },
    { code: '58', name: 'แม่ฮ่องสอน' },
    { code: '60', name: 'นครสวรรค์' },
    { code: '61', name: 'อุทัยธานี' },
    { code: '62', name: 'กำแพงเพชร' },
    { code: '63', name: 'ตาก' },
    { code: '64', name: 'สุโขทัย' },
    { code: '65', name: 'พิษณุโลก' },
    { code: '66', name: 'พิจิตร' },
    { code: '67', name: 'เพชรบูรณ์' },
    { code: '70', name: 'ราชบุรี' },
    { code: '71', name: 'กาญจนบุรี' },
    { code: '72', name: 'สุพรรณบุรี' },
    { code: '73', name: 'นครปฐม' },
    { code: '74', name: 'สมุทรสาคร' },
    { code: '75', name: 'สมุทรสงคราม' },
    { code: '76', name: 'เพชรบุรี' },
    { code: '77', name: 'ประจวบคีรีขันธ์' },
    { code: '80', name: 'นครศรีธรรมราช' },
    { code: '81', name: 'กระบี่' },
    { code: '82', name: 'พังงา' },
    { code: '83', name: 'ภูเก็ต' },
    { code: '84', name: 'สุราษฎร์ธานี' },
    { code: '85', name: 'ระนอง' },
    { code: '86', name: 'ชุมพร' },
    { code: '90', name: 'สงขลา' },
    { code: '91', name: 'สตูล' },
    { code: '92', name: 'ตรัง' },
    { code: '93', name: 'พัทลุง' },
    { code: '94', name: 'ปัตตานี' },
    { code: '95', name: 'ยะลา' },
    { code: '96', name: 'นราธิวาส' },
]


